
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomHeader } from "./components/header";
import { Sider } from "./components/sider";
import { MenuItem } from "./components/menu";
import { SiderWrapper } from "./components/mySider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clickitem1 = () => {
    console.log(111)
  };
  const clickItem2 = () => {
    console.log(222)
  };
  const items:MenuItem[] = [
    {
      label: <p>item 1 dropdown menu</p>,
      click: clickitem1,
      key: "item1",
    },
    {
      label: <p>item 2 modal open</p>,
      click: clickItem2,
      key: "item2",
    },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomHeader/>
 
    <SiderWrapper/>

        

        {children}
      </body>
    </html>
  );
}
